name: Aylal Local
values:
  - key: baseUrl
    value: 'http://localhost:5000'
    type: default
    enabled: true
  - key: MONGO_URI
    value: ''
    type: default
    enabled: true
  - key: JWT_SECRET
    value: ''
    type: default
    enabled: true
  - key: PORT
    value: '5000'
    type: default
    enabled: true
